#!/usr/bin/env bash
# Sovereign — first-time setup
# Run once before `docker compose up -d`
#
# Usage:
#   ./setup.sh              # core stack only
#   ./setup.sh --whatsapp   # include Matrix WhatsApp bridge

set -euo pipefail

WHATSAPP=0
for arg in "$@"; do
  [[ "$arg" == "--whatsapp" ]] && WHATSAPP=1
done

RED='\033[0;31m'; GREEN='\033[0;32m'; YELLOW='\033[1;33m'; RESET='\033[0m'
info()  { echo -e "${GREEN}▸${RESET} $*"; }
warn()  { echo -e "${YELLOW}⚠${RESET} $*"; }
error() { echo -e "${RED}✗${RESET} $*" >&2; exit 1; }

# ── Prerequisites ─────────────────────────────────────────────────────────────
command -v docker   >/dev/null 2>&1 || error "Docker is not installed."
command -v openssl  >/dev/null 2>&1 || error "openssl is required."
docker compose version >/dev/null 2>&1 || error "Docker Compose v2 is required."

info "Starting Sovereign setup…"

# ── .env ─────────────────────────────────────────────────────────────────────
if [[ ! -f .env ]]; then
  cp .env.example .env
  warn ".env created from .env.example — edit it before continuing."
  warn "At minimum set: DUMB_PHONE_NUMBER, TWILIO_*, and one connector token."
  echo ""
  echo "Press Enter when .env is ready, or Ctrl-C to abort."
  read -r
fi

# ── Generate random secrets for .env if placeholders remain ──────────────────
gen_secret() { openssl rand -hex 32; }

patch_env() {
  local key="$1"
  local value="$2"
  if grep -q "^${key}=CHANGE_ME" .env 2>/dev/null; then
    sed -i "s|^${key}=CHANGE_ME.*|${key}=${value}|" .env
    info "Generated ${key}"
  fi
}

# Twilio webhook secret (used to validate Twilio signature in connectors)
patch_env "TWILIO_WEBHOOK_SECRET" "$(gen_secret)"

# ── Ollama model ──────────────────────────────────────────────────────────────
info "Pulling Ollama LLM (llama3.2) — this may take several minutes on first run…"
docker compose pull ollama 2>/dev/null || true
# Model pull happens after first start (see Makefile: make ollama-pull)

# ── WhatsApp bridge setup ─────────────────────────────────────────────────────
if [[ "$WHATSAPP" -eq 1 ]]; then
  echo ""
  info "Setting up WhatsApp bridge (Matrix + mautrix-whatsapp)…"

  # Read server name from .env, fall back to sovereign.local
  MATRIX_SERVER_NAME=$(grep "^MATRIX_SERVER_NAME=" .env 2>/dev/null | cut -d= -f2 | tr -d '"' || echo "sovereign.local")
  if [[ -z "$MATRIX_SERVER_NAME" || "$MATRIX_SERVER_NAME" == "sovereign.local" ]]; then
    warn "MATRIX_SERVER_NAME not set in .env — using 'sovereign.local'."
    warn "This is fine for local/LAN use. For a public server, set your domain."
  fi

  # Generate secrets
  MATRIX_REG_SECRET=$(gen_secret)
  MATRIX_MACAROON=$(gen_secret)
  MATRIX_FORM_SECRET=$(gen_secret)
  MAUTRIX_AS_TOKEN=$(gen_secret)
  MAUTRIX_HS_TOKEN=$(gen_secret)

  # Patch homeserver.yaml
  HOMESERVER_YAML="synapse/homeserver.yaml"
  cp "${HOMESERVER_YAML}" "${HOMESERVER_YAML}.bak"
  sed -i \
    -e "s|SOVEREIGN_MATRIX_SERVER_NAME|${MATRIX_SERVER_NAME}|g" \
    -e "s|SOVEREIGN_REGISTRATION_SHARED_SECRET|${MATRIX_REG_SECRET}|g" \
    -e "s|SOVEREIGN_MACAROON_SECRET|${MATRIX_MACAROON}|g" \
    -e "s|SOVEREIGN_FORM_SECRET|${MATRIX_FORM_SECRET}|g" \
    "${HOMESERVER_YAML}"

  # Patch mautrix/config.yaml
  MAUTRIX_USER_ID=$(grep "^MATRIX_USER_ID=" .env 2>/dev/null | cut -d= -f2 | tr -d '"' || echo "@sovereign:${MATRIX_SERVER_NAME}")
  sed -i \
    -e "s|SOVEREIGN_MATRIX_SERVER_NAME|${MATRIX_SERVER_NAME}|g" \
    -e "s|SOVEREIGN_MAUTRIX_AS_TOKEN|${MAUTRIX_AS_TOKEN}|g" \
    -e "s|SOVEREIGN_MAUTRIX_HS_TOKEN|${MAUTRIX_HS_TOKEN}|g" \
    -e "s|SOVEREIGN_MATRIX_USER_ID|${MAUTRIX_USER_ID}|g" \
    mautrix/config.yaml

  # Patch mautrix/registration.yaml
  sed -i \
    -e "s|SOVEREIGN_MATRIX_SERVER_NAME|${MATRIX_SERVER_NAME}|g" \
    -e "s|SOVEREIGN_MAUTRIX_AS_TOKEN|${MAUTRIX_AS_TOKEN}|g" \
    -e "s|SOVEREIGN_MAUTRIX_HS_TOKEN|${MAUTRIX_HS_TOKEN}|g" \
    mautrix/registration.yaml

  # Write Synapse into the Docker volume with correct log config
  info "Initialising Synapse data volume…"
  docker compose --profile whatsapp run --rm \
    -v "$(pwd)/synapse/homeserver.yaml:/data/homeserver.yaml:ro" \
    -v "$(pwd)/synapse/log.config:/data/log.config:ro" \
    synapse generate 2>/dev/null || true

  # Copy our pre-configured homeserver.yaml into the volume
  docker compose --profile whatsapp run --rm \
    -v "$(pwd)/synapse/homeserver.yaml:/homeserver.yaml:ro" \
    --entrypoint "cp /homeserver.yaml /data/homeserver.yaml" \
    synapse 2>/dev/null || true

  # Copy log config
  docker compose --profile whatsapp run --rm \
    -v "$(pwd)/synapse/log.config:/log.config:ro" \
    --entrypoint "cp /log.config /data/log.config" \
    synapse 2>/dev/null || true

  # Patch .env with generated Matrix values
  {
    echo ""
    echo "# Generated by setup.sh"
    echo "MATRIX_SERVER_NAME=${MATRIX_SERVER_NAME}"
    echo "MATRIX_HOMESERVER_URL=http://synapse:8008"
    echo "WHATSAPP_BRIDGE_SECRET=${MAUTRIX_AS_TOKEN}"
  } >> .env

  info "WhatsApp bridge configured."
  echo ""
  warn "NEXT STEPS for WhatsApp:"
  warn "1. docker compose --profile whatsapp up -d"
  warn "2. docker compose logs -f mautrix   (wait for QR code)"
  warn "3. Scan the QR code with WhatsApp → Linked Devices → Link a Device"
  warn "4. WhatsApp messages will now flow through Sovereign."
fi

# ── Summary ───────────────────────────────────────────────────────────────────
echo ""
info "Setup complete."
echo ""
echo "  Start Sovereign:        docker compose up -d"
if [[ "$WHATSAPP" -eq 1 ]]; then
  echo "  Start with WhatsApp:    docker compose --profile whatsapp up -d"
fi
echo "  Open the interface:     http://localhost"
echo "  Pull Ollama model:      make ollama-pull   (after first start)"
echo "  View logs:              make logs"
echo ""
